import { DAY, HOUR, MINUTE, SECOND } from '@shared/constants';
import { TrackedItem } from '@shared/types';

const now = Date.now();

export const mockFreezedItems: TrackedItem[] = [
  {
    id: 'mock-1',
    account_id: 'mock-account',
    name: 'Wireless headphones',
    item_emoji: '🎧',
    price_usd: 89,
    price_currency: 'EUR',
    conversion_rate_snapshot: 1.08,
    status: 'frozen',
    freeze_until: new Date(now - 2 * HOUR).toISOString(),
    frozen_at: new Date(now - 3 * DAY).toISOString(),
    created_at: new Date(now - 3 * DAY).toISOString(),
    decided_at: null,
  },
  {
    id: 'mock-2',
    account_id: 'mock-account',
    name: 'Mountain bike helmet',
    item_emoji: '⛑️',
    price_usd: 124,
    price_currency: 'EUR',
    conversion_rate_snapshot: 1.08,
    status: 'frozen',
    freeze_until: new Date(now - 30 * MINUTE).toISOString(),
    frozen_at: new Date(now - 5 * DAY).toISOString(),
    created_at: new Date(now - 5 * DAY).toISOString(),
    decided_at: null,
  },
  {
    id: 'mock-3',
    account_id: 'mock-account',
    name: 'Vinyl record player',
    item_emoji: '🎵',
    price_usd: 340,
    price_currency: 'EUR',
    conversion_rate_snapshot: 1.08,
    status: 'frozen',
    freeze_until: new Date(now + 5 * HOUR + 12 * MINUTE).toISOString(),
    frozen_at: new Date(now - DAY).toISOString(),
    created_at: new Date(now - DAY).toISOString(),
    decided_at: null,
  },
  {
    id: 'mock-4',
    account_id: 'mock-account',
    name: 'Espresso machine',
    item_emoji: '☕',
    price_usd: 520,
    price_currency: 'EUR',
    conversion_rate_snapshot: 1.08,
    status: 'frozen',
    freeze_until: new Date(now + DAY + 4 * HOUR).toISOString(),
    frozen_at: new Date(now - 2 * DAY).toISOString(),
    created_at: new Date(now - 2 * DAY).toISOString(),
    decided_at: null,
  },
  {
    id: 'mock-5',
    account_id: 'mock-account',
    name: 'Hiking boots',
    item_emoji: '🥾',
    price_usd: 175,
    price_currency: 'EUR',
    conversion_rate_snapshot: 1.08,
    status: 'frozen',
    freeze_until: new Date(now + 5 * DAY + 22 * HOUR).toISOString(),
    frozen_at: new Date(now - DAY).toISOString(),
    created_at: new Date(now - DAY).toISOString(),
    decided_at: null,
  },
  {
    id: 'mock-6',
    account_id: 'mock-account',
    name: 'Smartwatch',
    item_emoji: '⌚',
    price_usd: 299,
    price_currency: 'CZK',
    conversion_rate_snapshot: 0.045,
    status: 'frozen',
    freeze_until: new Date(now + 6 * MINUTE).toISOString(),
    frozen_at: new Date(now - 3 * HOUR).toISOString(),
    created_at: new Date(now - 3 * HOUR).toISOString(),
    decided_at: null,
  },
  {
    id: 'mock-7',
    account_id: 'mock-account',
    name: 'Bluetooth speaker',
    item_emoji: '🔊',
    price_usd: 49,
    price_currency: 'CZK',
    conversion_rate_snapshot: 0.045,
    status: 'frozen',
    freeze_until: new Date(now + 15 * SECOND).toISOString(),
    frozen_at: new Date(now - 3 * HOUR).toISOString(),
    created_at: new Date(now - 3 * HOUR).toISOString(),
    decided_at: null,
  },
];
