export const accountLevels = [
  { level: 1, threshold: 0, tier: 'Aware', note: 'Starting to notice' },
  { level: 2, threshold: 3, tier: 'Aware', note: 'Building awareness' },
  { level: 3, threshold: 8, tier: 'Aware', note: 'Questioning impulses' },
  { level: 4, threshold: 15, tier: 'Aware', note: 'Seeing patterns' },
  { level: 5, threshold: 25, tier: 'Aware', note: 'Staying curious' },
  { level: 6, threshold: 40, tier: 'Mindful', note: 'Pausing before buying' },
  { level: 7, threshold: 60, tier: 'Mindful', note: 'Thinking it through' },
  { level: 8, threshold: 85, tier: 'Mindful', note: 'Choosing deliberately' },
  { level: 9, threshold: 115, tier: 'Mindful', note: 'Spending with intention' },
  { level: 10, threshold: 150, tier: 'Mindful', note: 'Mastering the pause' },
  { level: 11, threshold: 190, tier: 'Intentional', note: 'Living intentionally' },
  { level: 12, threshold: 230, tier: 'Intentional', note: 'Aligned spending' },
  { level: 13, threshold: 275, tier: 'Intentional', note: 'Values-led decisions' },
  { level: 14, threshold: 320, tier: 'Intentional', note: 'Beyond impulse' },
  { level: 15, threshold: 370, tier: 'Intentional', note: 'Conscious consumer' },
  { level: 16, threshold: 420, tier: 'Zen', note: 'At peace with money' },
  { level: 17, threshold: 470, tier: 'Zen', note: 'Effortless clarity' },
  { level: 18, threshold: 520, tier: 'Zen', note: 'Inner stillness' },
  { level: 19, threshold: 570, tier: 'Zen', note: 'Wisdom in action' },
  { level: 20, threshold: 600, tier: 'Zen', note: 'The Zen master' },
] as const;
