export const accountLevels = [
  { level: 1, threshold: 0, tier: 'Aware' },
  { level: 2, threshold: 3, tier: 'Aware' },
  { level: 3, threshold: 8, tier: 'Aware' },
  { level: 4, threshold: 15, tier: 'Aware' },
  { level: 5, threshold: 25, tier: 'Aware' },
  { level: 6, threshold: 40, tier: 'Mindful' },
  { level: 7, threshold: 60, tier: 'Mindful' },
  { level: 8, threshold: 85, tier: 'Mindful' },
  { level: 9, threshold: 115, tier: 'Mindful' },
  { level: 10, threshold: 150, tier: 'Mindful' },
  { level: 11, threshold: 190, tier: 'Intentional' },
  { level: 12, threshold: 230, tier: 'Intentional' },
  { level: 13, threshold: 275, tier: 'Intentional' },
  { level: 14, threshold: 320, tier: 'Intentional' },
  { level: 15, threshold: 370, tier: 'Intentional' },
  { level: 16, threshold: 420, tier: 'Zen' },
  { level: 17, threshold: 470, tier: 'Zen' },
  { level: 18, threshold: 520, tier: 'Zen' },
  { level: 19, threshold: 570, tier: 'Zen' },
  { level: 20, threshold: 600, tier: 'Zen' },
] as const;
