-- =============================================================================
-- BadBuy — Supabase Initialization Script
-- Based on: ADR-004 + Technical Documentation
-- Safe to re-run: uses CREATE IF NOT EXISTS / DO $$ blocks throughout
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 0. Extensions
-- -----------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS "pgcrypto";  -- for gen_random_uuid()


-- =============================================================================
-- 1. ENUMS
-- =============================================================================

DO $$ BEGIN
  CREATE TYPE tracked_item_status AS ENUM ('frozen', 'bought', 'skipped');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE notification_type AS ENUM ('freeze_thawed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- =============================================================================
-- 2. TABLES
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 2.1 Predefined Hobbies
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS predefined_hobby (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  name         text        NOT NULL UNIQUE,
  lucide_icon  text        NOT NULL,
  category     text        NOT NULL,
  sort_order   integer     NOT NULL DEFAULT 0
);

-- -----------------------------------------------------------------------------
-- 2.2 Promo Codes
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS promo_code (
  id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  code                    text        NOT NULL UNIQUE,
  premium_months_granted  integer     NOT NULL DEFAULT 3,
  max_uses                integer,                          -- NULL = unlimited
  current_uses            integer     NOT NULL DEFAULT 0,
  is_active               boolean     NOT NULL DEFAULT true,
  expires_at              timestamptz,                      -- NULL = no expiry
  created_at              timestamptz NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 2.3 Account
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS account (
  id                      uuid        PRIMARY KEY,          -- = auth.uid()
  name                    text,                             -- null until onboarding is complete
  avatar_seed             text,                             -- defaults to id via trigger
  birthdate               date,
  country                 text,                             -- ISO 3166-1 alpha-2
  display_currency        text,                             -- ISO 4217; derived from country
  wage_currency           text,                             -- ISO 4217; currency wage was entered in
  hourly_wage_usd         decimal,                          -- always in USD
  work_hours_per_day      decimal     NOT NULL DEFAULT 8,
  notifications_enabled   boolean     NOT NULL DEFAULT true,
  premium_expires_at      timestamptz,                      -- NULL = free account
  referral_code           text        UNIQUE,               -- generated by trigger on INSERT
  decision_count          integer     NOT NULL DEFAULT 0,   -- skip + buy; synced via trigger
  is_onboarding_complete  boolean     NOT NULL DEFAULT false,
  created_at              timestamptz NOT NULL DEFAULT now()
);

-- Trigger: set avatar_seed = id and generate referral_code on INSERT
CREATE OR REPLACE FUNCTION trg_account_before_insert()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  candidate text;
  attempts  integer := 0;
BEGIN
  -- Default avatar_seed to the account's own UUID
  IF NEW.avatar_seed IS NULL THEN
    NEW.avatar_seed := NEW.id::text;
  END IF;

  -- Generate a unique 6-char uppercase alphanumeric referral code
  LOOP
    candidate := upper(substring(replace(gen_random_uuid()::text, '-', ''), 1, 6));
    EXIT WHEN NOT EXISTS (SELECT 1 FROM account WHERE referral_code = candidate);
    attempts := attempts + 1;
    IF attempts > 10 THEN
      RAISE EXCEPTION 'Could not generate unique referral_code after 10 attempts';
    END IF;
  END LOOP;
  NEW.referral_code := candidate;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS account_before_insert ON account;
CREATE TRIGGER account_before_insert
  BEFORE INSERT ON account
  FOR EACH ROW EXECUTE FUNCTION trg_account_before_insert();

-- -----------------------------------------------------------------------------
-- 2.4 account_hobby
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS account_hobby (
  id                   uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id           uuid        NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  hobby_name           text        NOT NULL,
  predefined_hobby_id  uuid        REFERENCES predefined_hobby(id) ON DELETE SET NULL,
  is_moderated         boolean     NOT NULL DEFAULT false,
  created_at           timestamptz NOT NULL DEFAULT now(),

  UNIQUE (account_id, hobby_name)
);

-- -----------------------------------------------------------------------------
-- 2.5 account_suggestion
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS account_suggestion (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  hobby_id      uuid        NOT NULL REFERENCES account_hobby(id) ON DELETE CASCADE,
  name          text        NOT NULL,
  item_emoji    text,
  price_usd     decimal     NOT NULL,
  country       text        NOT NULL,   -- denormalized cache key
  generated_at  timestamptz NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 2.6 tracked_item
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tracked_item (
  id                        uuid                 PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id                uuid                 NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  name                      text,                                    -- set at freeze time
  item_emoji                text,
  price_usd                 decimal              NOT NULL,
  price_currency            text                 NOT NULL,
  conversion_rate_snapshot  decimal              NOT NULL,
  status                    tracked_item_status  NOT NULL DEFAULT 'frozen',
  freeze_until              timestamptz,
  frozen_at                 timestamptz,
  created_at                timestamptz          NOT NULL DEFAULT now(),
  decided_at                timestamptz
);

-- Trigger: keep account.decision_count in sync when status changes to bought/skipped
CREATE OR REPLACE FUNCTION trg_tracked_item_decision_count()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  -- On INSERT with a terminal status
  IF TG_OP = 'INSERT' AND NEW.status IN ('bought', 'skipped') THEN
    UPDATE account SET decision_count = decision_count + 1 WHERE id = NEW.account_id;

  -- On UPDATE where status transitions INTO a terminal state
  ELSIF TG_OP = 'UPDATE'
    AND OLD.status = 'frozen'
    AND NEW.status IN ('bought', 'skipped') THEN
    UPDATE account SET decision_count = decision_count + 1 WHERE id = NEW.account_id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tracked_item_decision_count ON tracked_item;
CREATE TRIGGER tracked_item_decision_count
  AFTER INSERT OR UPDATE OF status ON tracked_item
  FOR EACH ROW EXECUTE FUNCTION trg_tracked_item_decision_count();

-- -----------------------------------------------------------------------------
-- 2.7 Currency Rates
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS currency_rate (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  base        text        NOT NULL DEFAULT 'USD',
  target      text        NOT NULL,
  rate        decimal     NOT NULL,
  fetched_at  timestamptz NOT NULL DEFAULT now(),

  UNIQUE (base, target)
);

-- -----------------------------------------------------------------------------
-- 2.8 Referral Redemptions
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS referral_redemption (
  id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  redeemer_account_id     uuid        NOT NULL REFERENCES account(id),
  referrer_account_id     uuid        REFERENCES account(id),          -- NULL if seed code used
  promo_code_id           uuid        REFERENCES promo_code(id),       -- NULL if user referral used
  premium_months_granted  integer     NOT NULL DEFAULT 3,
  redeemed_at             timestamptz NOT NULL DEFAULT now(),

  -- One redemption per account, ever
  UNIQUE (redeemer_account_id),

  -- Exactly one of the two code columns must be populated
  CONSTRAINT chk_referral_xor_promo
    CHECK (num_nonnulls(referrer_account_id, promo_code_id) = 1),

  -- No self-referral
  CONSTRAINT chk_no_self_referral
    CHECK (redeemer_account_id != referrer_account_id)
);

-- -----------------------------------------------------------------------------
-- 2.9 Notifications
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS notification (
  id              uuid               PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id      uuid               NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  type            notification_type  NOT NULL,
  tracked_item_id uuid               NOT NULL REFERENCES tracked_item(id) ON DELETE CASCADE,
  created_at      timestamptz        NOT NULL DEFAULT now(),
  read_at         timestamptz                                           -- NULL = unread
);


-- =============================================================================
-- 3. INDEXES
-- =============================================================================

-- account_hobby
CREATE INDEX IF NOT EXISTS idx_account_hobby_account_id  ON account_hobby(account_id);
CREATE INDEX IF NOT EXISTS idx_account_hobby_predefined   ON account_hobby(predefined_hobby_id);

-- account_suggestion
CREATE INDEX IF NOT EXISTS idx_suggestion_hobby_id        ON account_suggestion(hobby_id);

-- tracked_item
CREATE INDEX IF NOT EXISTS idx_tracked_item_account_id    ON tracked_item(account_id);
CREATE INDEX IF NOT EXISTS idx_tracked_item_status        ON tracked_item(status);
-- Used by process-thawed-items cron: frozen items whose timer has elapsed
CREATE INDEX IF NOT EXISTS idx_tracked_item_frozen_thawed
  ON tracked_item(status, freeze_until)
  WHERE status = 'frozen';

-- notification
CREATE INDEX IF NOT EXISTS idx_notification_account_id    ON notification(account_id);
CREATE INDEX IF NOT EXISTS idx_notification_unread
  ON notification(account_id, read_at)
  WHERE read_at IS NULL;

-- currency_rate
CREATE INDEX IF NOT EXISTS idx_currency_rate_target       ON currency_rate(target);


-- =============================================================================
-- 4. ROW LEVEL SECURITY
-- =============================================================================

-- Enable RLS on all tables that contain account data
ALTER TABLE account             ENABLE ROW LEVEL SECURITY;
ALTER TABLE account_hobby       ENABLE ROW LEVEL SECURITY;
ALTER TABLE account_suggestion  ENABLE ROW LEVEL SECURITY;
ALTER TABLE tracked_item        ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification        ENABLE ROW LEVEL SECURITY;
ALTER TABLE referral_redemption ENABLE ROW LEVEL SECURITY;
ALTER TABLE promo_code          ENABLE ROW LEVEL SECURITY;
ALTER TABLE predefined_hobby    ENABLE ROW LEVEL SECURITY;
ALTER TABLE currency_rate       ENABLE ROW LEVEL SECURITY;

-- -----------------------------------------------------------------------------
-- Public reference data — SELECT for anon + authenticated only
-- No INSERT/UPDATE/DELETE policies: clients cannot mutate these tables.
-- Edge Functions and jobs use the service role, which bypasses RLS.
-- -----------------------------------------------------------------------------

DROP POLICY IF EXISTS predefined_hobby_select_public ON predefined_hobby;
CREATE POLICY predefined_hobby_select_public ON predefined_hobby
  FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS currency_rate_select_public ON currency_rate;
CREATE POLICY currency_rate_select_public ON currency_rate
  FOR SELECT TO anon, authenticated
  USING (true);

-- -----------------------------------------------------------------------------
-- 4.1 Account
-- -----------------------------------------------------------------------------

DROP POLICY IF EXISTS account_select_own ON account;
CREATE POLICY account_select_own ON account
  FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS account_insert_own ON account;
CREATE POLICY account_insert_own ON account
  FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS account_update_own ON account;
CREATE POLICY account_update_own ON account
  FOR UPDATE USING (auth.uid() = id);

-- -----------------------------------------------------------------------------
-- 4.2 Account Hobby
-- -----------------------------------------------------------------------------

DROP POLICY IF EXISTS account_hobby_select_own ON account_hobby;
CREATE POLICY account_hobby_select_own ON account_hobby
  FOR SELECT USING (auth.uid() = account_id);

DROP POLICY IF EXISTS account_hobby_insert_own ON account_hobby;
CREATE POLICY account_hobby_insert_own ON account_hobby
  FOR INSERT WITH CHECK (auth.uid() = account_id);

DROP POLICY IF EXISTS account_hobby_update_own ON account_hobby;
CREATE POLICY account_hobby_update_own ON account_hobby
  FOR UPDATE USING (auth.uid() = account_id);

DROP POLICY IF EXISTS account_hobby_delete_own ON account_hobby;
CREATE POLICY account_hobby_delete_own ON account_hobby
  FOR DELETE USING (auth.uid() = account_id);

-- -----------------------------------------------------------------------------
-- 4.3 Account Suggestion
-- -----------------------------------------------------------------------------

DROP POLICY IF EXISTS account_suggestion_select_own ON account_suggestion;
CREATE POLICY account_suggestion_select_own ON account_suggestion
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM account_hobby
      WHERE account_hobby.id = account_suggestion.hobby_id
        AND account_hobby.account_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS account_suggestion_insert_own ON account_suggestion;
CREATE POLICY account_suggestion_insert_own ON account_suggestion
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM account_hobby
      WHERE account_hobby.id = account_suggestion.hobby_id
        AND account_hobby.account_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS account_suggestion_delete_own ON account_suggestion;
CREATE POLICY account_suggestion_delete_own ON account_suggestion
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM account_hobby
      WHERE account_hobby.id = account_suggestion.hobby_id
        AND account_hobby.account_id = auth.uid()
    )
  );

-- -----------------------------------------------------------------------------
-- 4.4 Tracked Item
-- -----------------------------------------------------------------------------

DROP POLICY IF EXISTS tracked_item_select_own ON tracked_item;
CREATE POLICY tracked_item_select_own ON tracked_item
  FOR SELECT USING (auth.uid() = account_id);

DROP POLICY IF EXISTS tracked_item_insert_own ON tracked_item;
CREATE POLICY tracked_item_insert_own ON tracked_item
  FOR INSERT WITH CHECK (auth.uid() = account_id);

DROP POLICY IF EXISTS tracked_item_update_own ON tracked_item;
CREATE POLICY tracked_item_update_own ON tracked_item
  FOR UPDATE USING (auth.uid() = account_id);

DROP POLICY IF EXISTS tracked_item_delete_own ON tracked_item;
CREATE POLICY tracked_item_delete_own ON tracked_item
  FOR DELETE USING (auth.uid() = account_id);

-- -----------------------------------------------------------------------------
-- Notification
-- -----------------------------------------------------------------------------

DROP POLICY IF EXISTS notification_select_own ON notification;
CREATE POLICY notification_select_own ON notification
  FOR SELECT USING (auth.uid() = account_id);

DROP POLICY IF EXISTS notification_update_own ON notification;
CREATE POLICY notification_update_own ON notification
  FOR UPDATE USING (auth.uid() = account_id);

-- -----------------------------------------------------------------------------
-- Referral Redemption
-- -----------------------------------------------------------------------------

DROP POLICY IF EXISTS referral_redemption_select_own ON referral_redemption;
CREATE POLICY referral_redemption_select_own ON referral_redemption
  FOR SELECT USING (
    auth.uid() = redeemer_account_id
    OR auth.uid() = referrer_account_id
  );

-- =============================================================================
-- 5. SEED DATA
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 5.1 Predefined Hobbies (~40 hobbies across ~6 categories)
-- -----------------------------------------------------------------------------

INSERT INTO predefined_hobby (name, lucide_icon, category, sort_order) VALUES
  -- Sports
  ('Cycling',          'Bike',          'Sports',   10),
  ('Running',          'PersonStanding','Sports',   20),
  ('Hiking',           'Mountain',      'Sports',   30),
  ('Yoga',             'Flower2',       'Sports',   40),
  ('Swimming',         'Waves',         'Sports',   50),
  ('Football',         'CircleDot',     'Sports',   60),
  ('Basketball',       'Circle',        'Sports',   70),
  ('Tennis',           'Circle',        'Sports',   80),

  -- Music
  ('Guitar',           'Music',         'Music',    10),
  ('Piano',            'Music',         'Music',    20),
  ('Singing',          'Mic',           'Music',    30),
  ('DJing',            'Disc3',         'Music',    40),
  ('Drums',            'Music',         'Music',    50),

  -- Food & Drink
  ('Cooking',          'ChefHat',       'Food',     10),
  ('Coffee',           'Coffee',        'Food',     20),
  ('Wine',             'Wine',          'Food',     30),
  ('Baking',           'Cookie',        'Food',     40),
  ('Cocktails',        'GlassWater',    'Food',     50),

  -- Creative
  ('Photography',      'Camera',        'Creative', 10),
  ('Painting',         'Paintbrush',    'Creative', 20),
  ('Reading',          'BookOpen',      'Creative', 30),
  ('Writing',          'PenLine',       'Creative', 40),
  ('Drawing',          'Pencil',        'Creative', 50),
  ('Knitting',         'Scissors',      'Creative', 60),
  ('Pottery',          'Circle',        'Creative', 70),

  -- Tech
  ('Gaming',           'Gamepad2',      'Tech',     10),
  ('PC Building',      'Cpu',           'Tech',     20),
  ('Coding',           'Code2',         'Tech',     30),
  ('3D Printing',      'Box',           'Tech',     40),
  ('Electronics',      'Zap',           'Tech',     50),
  ('Robotics',         'Bot',           'Tech',     60),

  -- Outdoors
  ('Travel',           'Plane',         'Outdoors', 10),
  ('Camping',          'Tent',          'Outdoors', 20),
  ('Gardening',        'Flower',        'Outdoors', 30),
  ('Fishing',          'Fish',          'Outdoors', 40),
  ('Climbing',         'Mountain',      'Outdoors', 50),
  ('Surfing',          'Waves',         'Outdoors', 60),
  ('Skateboarding',    'CircleDot',     'Outdoors', 70)

ON CONFLICT (name) DO NOTHING;

-- -----------------------------------------------------------------------------
-- 5.2 Promo Codes
-- -----------------------------------------------------------------------------

INSERT INTO promo_code (code, premium_months_granted, max_uses, is_active, expires_at) VALUES
  ('LAUNCH2026', 3, NULL, true, '2026-12-31 23:59:59+00')

ON CONFLICT (code) DO NOTHING;
