-- =============================================================================
-- ISO 3166-1 alpha-2 countries with their default (primary) currency.
-- Used on the onboarding country picker and to pre-fill display currency.
-- =============================================================================

CREATE TABLE IF NOT EXISTS country (
  code              text PRIMARY KEY,           -- ISO 3166-1 alpha-2
  name              text        NOT NULL,
  default_currency  text        NOT NULL REFERENCES currency(code)
);

-- No RLS needed — country is public read-only reference data.

INSERT INTO country (code, name, default_currency) VALUES
  -- Europe – Eurozone
  ('AD', 'Andorra',                   'EUR'),
  ('AT', 'Austria',                   'EUR'),
  ('BE', 'Belgium',                   'EUR'),
  ('HR', 'Croatia',                   'EUR'),
  ('CY', 'Cyprus',                    'EUR'),
  ('EE', 'Estonia',                   'EUR'),
  ('FI', 'Finland',                   'EUR'),
  ('FR', 'France',                    'EUR'),
  ('DE', 'Germany',                   'EUR'),
  ('GR', 'Greece',                    'EUR'),
  ('IE', 'Ireland',                   'EUR'),
  ('IT', 'Italy',                     'EUR'),
  ('XK', 'Kosovo',                    'EUR'),
  ('LV', 'Latvia',                    'EUR'),
  ('LT', 'Lithuania',                 'EUR'),
  ('LU', 'Luxembourg',                'EUR'),
  ('MT', 'Malta',                     'EUR'),
  ('MC', 'Monaco',                    'EUR'),
  ('ME', 'Montenegro',                'EUR'),
  ('NL', 'Netherlands',               'EUR'),
  ('PT', 'Portugal',                  'EUR'),
  ('SM', 'San Marino',                'EUR'),
  ('SK', 'Slovakia',                  'EUR'),
  ('SI', 'Slovenia',                  'EUR'),
  ('ES', 'Spain',                     'EUR'),
  ('VA', 'Vatican City',              'EUR'),

  -- Europe – non-Eurozone
  ('AL', 'Albania',                   'ALL'),
  ('BY', 'Belarus',                   'BYN'),
  ('BA', 'Bosnia and Herzegovina',    'BAM'),
  ('BG', 'Bulgaria',                   'EUR'),
  ('CZ', 'Czechia',                   'CZK'),
  ('DK', 'Denmark',                   'DKK'),
  ('GE', 'Georgia',                   'GEL'),
  ('GB', 'United Kingdom',            'GBP'),
  ('HU', 'Hungary',                   'HUF'),
  ('IS', 'Iceland',                   'ISK'),
  ('MD', 'Moldova',                   'MDL'),
  ('MK', 'North Macedonia',           'MKD'),
  ('NO', 'Norway',                    'NOK'),
  ('PL', 'Poland',                    'PLN'),
  ('RO', 'Romania',                   'RON'),
  ('RS', 'Serbia',                    'RSD'),
  ('SE', 'Sweden',                    'SEK'),
  ('CH', 'Switzerland',               'CHF'),
  ('UA', 'Ukraine',                   'UAH'),

  -- Americas
  ('AR', 'Argentina',                 'ARS'),
  ('BS', 'Bahamas',                   'BSD'),
  ('BB', 'Barbados',                  'BBD'),
  ('BZ', 'Belize',                    'BZD'),
  ('BO', 'Bolivia',                   'BOB'),
  ('BR', 'Brazil',                    'BRL'),
  ('CA', 'Canada',                    'CAD'),
  ('CL', 'Chile',                     'CLP'),
  ('CO', 'Colombia',                  'COP'),
  ('CR', 'Costa Rica',                'CRC'),
  ('CU', 'Cuba',                      'CUP'),
  ('DO', 'Dominican Republic',        'DOP'),
  ('EC', 'Ecuador',                   'USD'),
  ('SV', 'El Salvador',               'USD'),
  ('GT', 'Guatemala',                 'GTQ'),
  ('GY', 'Guyana',                    'GYD'),
  ('HT', 'Haiti',                     'HTG'),
  ('HN', 'Honduras',                  'HNL'),
  ('JM', 'Jamaica',                   'JMD'),
  ('MX', 'Mexico',                    'MXN'),
  ('NI', 'Nicaragua',                 'NIO'),
  ('PA', 'Panama',                    'PAB'),
  ('PY', 'Paraguay',                  'PYG'),
  ('PE', 'Peru',                      'PEN'),
  ('SR', 'Suriname',                  'SRD'),
  ('TT', 'Trinidad and Tobago',       'TTD'),
  ('US', 'United States',             'USD'),
  ('UY', 'Uruguay',                   'UYU'),
  ('VE', 'Venezuela',                 'VED'),

  -- Asia & Middle East
  ('AF', 'Afghanistan',               'AFN'),
  ('AM', 'Armenia',                   'AMD'),
  ('AZ', 'Azerbaijan',                'AZN'),
  ('BH', 'Bahrain',                   'BHD'),
  ('BD', 'Bangladesh',                'BDT'),
  ('BT', 'Bhutan',                    'BTN'),
  ('BN', 'Brunei',                    'BND'),
  ('KH', 'Cambodia',                  'KHR'),
  ('CN', 'China',                     'CNY'),
  ('HK', 'Hong Kong',                 'HKD'),
  ('IN', 'India',                     'INR'),
  ('ID', 'Indonesia',                 'IDR'),
  ('IR', 'Iran',                      'IRR'),
  ('IQ', 'Iraq',                      'IQD'),
  ('IL', 'Israel',                    'ILS'),
  ('JP', 'Japan',                     'JPY'),
  ('JO', 'Jordan',                    'JOD'),
  ('KZ', 'Kazakhstan',                'KZT'),
  ('KP', 'North Korea',               'KPW'),
  ('KR', 'South Korea',               'KRW'),
  ('KW', 'Kuwait',                    'KWD'),
  ('KG', 'Kyrgyzstan',                'KGS'),
  ('LA', 'Laos',                      'LAK'),
  ('LB', 'Lebanon',                   'LBP'),
  ('MO', 'Macao',                     'MOP'),
  ('MY', 'Malaysia',                  'MYR'),
  ('MV', 'Maldives',                  'MVR'),
  ('MN', 'Mongolia',                  'MNT'),
  ('MM', 'Myanmar',                   'MMK'),
  ('NP', 'Nepal',                     'NPR'),
  ('OM', 'Oman',                      'OMR'),
  ('PK', 'Pakistan',                  'PKR'),
  ('PH', 'Philippines',               'PHP'),
  ('QA', 'Qatar',                     'QAR'),
  ('SA', 'Saudi Arabia',              'SAR'),
  ('SG', 'Singapore',                 'SGD'),
  ('LK', 'Sri Lanka',                 'LKR'),
  ('SY', 'Syria',                     'SYP'),
  ('TW', 'Taiwan',                    'TWD'),
  ('TJ', 'Tajikistan',                'TJS'),
  ('TH', 'Thailand',                  'THB'),
  ('TL', 'Timor-Leste',               'USD'),
  ('TM', 'Turkmenistan',              'TMT'),
  ('TR', 'Turkey',                    'TRY'),
  ('AE', 'United Arab Emirates',      'AED'),
  ('UZ', 'Uzbekistan',                'UZS'),
  ('VN', 'Vietnam',                   'VND'),
  ('YE', 'Yemen',                     'YER'),

  -- Africa
  ('DZ', 'Algeria',                   'DZD'),
  ('AO', 'Angola',                    'AOA'),
  ('BJ', 'Benin',                     'XOF'),
  ('BW', 'Botswana',                  'BWP'),
  ('BF', 'Burkina Faso',              'XOF'),
  ('BI', 'Burundi',                   'BIF'),
  ('CM', 'Cameroon',                  'XAF'),
  ('CV', 'Cape Verde',                'CVE'),
  ('CF', 'Central African Republic',  'XAF'),
  ('TD', 'Chad',                      'XAF'),
  ('KM', 'Comoros',                   'KMF'),
  ('CG', 'Republic of the Congo',     'XAF'),
  ('CD', 'DR Congo',                  'CDF'),
  ('CI', 'Côte d''Ivoire',            'XOF'),
  ('DJ', 'Djibouti',                  'DJF'),
  ('EG', 'Egypt',                     'EGP'),
  ('GQ', 'Equatorial Guinea',         'XAF'),
  ('ER', 'Eritrea',                   'ERN'),
  ('SZ', 'Eswatini',                  'SZL'),
  ('ET', 'Ethiopia',                  'ETB'),
  ('GA', 'Gabon',                     'XAF'),
  ('GM', 'Gambia',                    'GMD'),
  ('GH', 'Ghana',                     'GHS'),
  ('GN', 'Guinea',                    'GNF'),
  ('GW', 'Guinea-Bissau',             'XOF'),
  ('KE', 'Kenya',                     'KES'),
  ('LS', 'Lesotho',                   'LSL'),
  ('LR', 'Liberia',                   'LRD'),
  ('LY', 'Libya',                     'LYD'),
  ('MG', 'Madagascar',                'MGA'),
  ('MW', 'Malawi',                    'MWK'),
  ('ML', 'Mali',                      'XOF'),
  ('MR', 'Mauritania',                'MRU'),
  ('MU', 'Mauritius',                 'MUR'),
  ('MA', 'Morocco',                   'MAD'),
  ('MZ', 'Mozambique',                'MZN'),
  ('NA', 'Namibia',                   'NAD'),
  ('NE', 'Niger',                     'XOF'),
  ('NG', 'Nigeria',                   'NGN'),
  ('RW', 'Rwanda',                    'RWF'),
  ('ST', 'São Tomé and Príncipe',     'STN'),
  ('SN', 'Senegal',                   'XOF'),
  ('SC', 'Seychelles',                'SCR'),
  ('SL', 'Sierra Leone',              'SLE'),
  ('SO', 'Somalia',                   'SOS'),
  ('ZA', 'South Africa',              'ZAR'),
  ('SS', 'South Sudan',               'SSP'),
  ('SD', 'Sudan',                     'SDG'),
  ('TZ', 'Tanzania',                  'TZS'),
  ('TG', 'Togo',                      'XOF'),
  ('TN', 'Tunisia',                   'TND'),
  ('UG', 'Uganda',                    'UGX'),
  ('ZM', 'Zambia',                    'ZMW'),
  ('ZW', 'Zimbabwe',                  'ZWG'),

  -- Oceania
  ('AU', 'Australia',                 'AUD'),
  ('FJ', 'Fiji',                      'FJD'),
  ('KI', 'Kiribati',                  'AUD'),
  ('MH', 'Marshall Islands',          'USD'),
  ('FM', 'Micronesia',                'USD'),
  ('NR', 'Nauru',                     'AUD'),
  ('NZ', 'New Zealand',               'NZD'),
  ('PW', 'Palau',                     'USD'),
  ('PG', 'Papua New Guinea',          'PGK'),
  ('WS', 'Samoa',                     'WST'),
  ('SB', 'Solomon Islands',           'SBD'),
  ('TO', 'Tonga',                     'TOP'),
  ('TV', 'Tuvalu',                    'AUD'),
  ('VU', 'Vanuatu',                   'VUV')
ON CONFLICT (code) DO NOTHING;
