-- Seed data for the currency table.
-- Source: ISO 4217 via https://www.iban.com/currency-codes
-- One row per unique currency code; entries with no code (e.g. Antarctica) are omitted.

INSERT INTO currency (code, name, symbol) VALUES
  ('AED', 'UAE Dirham',                                    'د.إ'),
  ('AFN', 'Afghani',                                       '؋'),
  ('ALL', 'Lek',                                           'L'),
  ('AMD', 'Armenian Dram',                                 '֏'),
  ('AOA', 'Kwanza',                                        'Kz'),
  ('ARS', 'Argentine Peso',                                '$'),
  ('AUD', 'Australian Dollar',                             '$'),
  ('AWG', 'Aruban Florin',                                 'ƒ'),
  ('AZN', 'Azerbaijanian Manat',                           '₼'),
  ('BAM', 'Convertible Mark',                              'KM'),
  ('BBD', 'Barbados Dollar',                               '$'),
  ('BDT', 'Taka',                                          '৳'),
  ('BHD', 'Bahraini Dinar',                                '.د.ب'),
  ('BIF', 'Burundi Franc',                                 'Fr'),
  ('BMD', 'Bermudian Dollar',                              '$'),
  ('BND', 'Brunei Dollar',                                 '$'),
  ('BOB', 'Boliviano',                                     'Bs.'),
  ('BOV', 'Mvdol',                                         'BOV'),
  ('BRL', 'Brazilian Real',                                'R$'),
  ('BSD', 'Bahamian Dollar',                               '$'),
  ('BTN', 'Ngultrum',                                      'Nu'),
  ('BWP', 'Pula',                                          'P'),
  ('BYN', 'Belarussian Ruble',                             'Br'),
  ('BZD', 'Belize Dollar',                                 '$'),
  ('CAD', 'Canadian Dollar',                               '$'),
  ('CDF', 'Congolese Franc',                               'Fr'),
  ('CHE', 'WIR Euro',                                      'CHE'),
  ('CHF', 'Swiss Franc',                                   'Fr'),
  ('CHW', 'WIR Franc',                                     'CHW'),
  ('CLF', 'Unidad de Fomento',                             'UF'),
  ('CLP', 'Chilean Peso',                                  '$'),
  ('CNY', 'Yuan Renminbi',                                 '¥'),
  ('COP', 'Colombian Peso',                                '$'),
  ('COU', 'Unidad de Valor Real',                          'COU'),
  ('CRC', 'Costa Rican Colon',                             '₡'),
  ('CUC', 'Peso Convertible',                              '$'),
  ('CUP', 'Cuban Peso',                                    '$'),
  ('CVE', 'Cabo Verde Escudo',                             '$'),
  ('CZK', 'Czech Koruna',                                  'Kč'),
  ('DJF', 'Djibouti Franc',                                'Fr'),
  ('DKK', 'Danish Krone',                                  'kr'),
  ('DOP', 'Dominican Peso',                                '$'),
  ('DZD', 'Algerian Dinar',                                'دج'),
  ('EGP', 'Egyptian Pound',                                '£'),
  ('ERN', 'Nakfa',                                         'Nkf'),
  ('ETB', 'Ethiopian Birr',                                'Br'),
  ('EUR', 'Euro',                                          '€'),
  ('FJD', 'Fiji Dollar',                                   '$'),
  ('FKP', 'Falkland Islands Pound',                        '£'),
  ('GBP', 'Pound Sterling',                                '£'),
  ('GEL', 'Lari',                                          '₾'),
  ('GHS', 'Ghana Cedi',                                    '₵'),
  ('GIP', 'Gibraltar Pound',                               '£'),
  ('GMD', 'Dalasi',                                        'D'),
  ('GNF', 'Guinea Franc',                                  'Fr'),
  ('GTQ', 'Quetzal',                                       'Q'),
  ('GYD', 'Guyana Dollar',                                 '$'),
  ('HKD', 'Hong Kong Dollar',                              '$'),
  ('HNL', 'Lempira',                                       'L'),
  ('HTG', 'Gourde',                                        'G'),
  ('HUF', 'Forint',                                        'Ft'),
  ('IDR', 'Rupiah',                                        'Rp'),
  ('ILS', 'New Israeli Sheqel',                            '₪'),
  ('INR', 'Indian Rupee',                                  '₹'),
  ('IQD', 'Iraqi Dinar',                                   'ع.د'),
  ('IRR', 'Iranian Rial',                                  '﷼'),
  ('ISK', 'Iceland Krona',                                 'kr'),
  ('JMD', 'Jamaican Dollar',                               '$'),
  ('JOD', 'Jordanian Dinar',                               'JD'),
  ('JPY', 'Yen',                                           '¥'),
  ('KES', 'Kenyan Shilling',                               'KSh'),
  ('KGS', 'Som',                                           'с'),
  ('KHR', 'Riel',                                          '៛'),
  ('KMF', 'Comoro Franc',                                  'Fr'),
  ('KPW', 'North Korean Won',                              '₩'),
  ('KRW', 'Won',                                           '₩'),
  ('KWD', 'Kuwaiti Dinar',                                 'KD'),
  ('KYD', 'Cayman Islands Dollar',                         '$'),
  ('KZT', 'Tenge',                                         '₸'),
  ('LAK', 'Kip',                                           '₭'),
  ('LBP', 'Lebanese Pound',                                '£'),
  ('LKR', 'Sri Lanka Rupee',                               '₨'),
  ('LRD', 'Liberian Dollar',                               '$'),
  ('LSL', 'Loti',                                          'L'),
  ('LYD', 'Libyan Dinar',                                  'ل.د'),
  ('MAD', 'Moroccan Dirham',                               'MAD'),
  ('MDL', 'Moldovan Leu',                                  'L'),
  ('MGA', 'Malagasy Ariary',                               'Ar'),
  ('MKD', 'Denar',                                         'ден'),
  ('MMK', 'Kyat',                                          'K'),
  ('MNT', 'Tugrik',                                        '₮'),
  ('MOP', 'Pataca',                                        'P'),
  ('MRU', 'Ouguiya',                                       'UM'),
  ('MUR', 'Mauritius Rupee',                               '₨'),
  ('MVR', 'Rufiyaa',                                       'Rf'),
  ('MWK', 'Kwacha',                                        'MK'),
  ('MXN', 'Mexican Peso',                                  '$'),
  ('MXV', 'Mexican Unidad de Inversion (UDI)',             'MXV'),
  ('MYR', 'Malaysian Ringgit',                             'RM'),
  ('MZN', 'Mozambique Metical',                            'MT'),
  ('NAD', 'Namibia Dollar',                                '$'),
  ('NGN', 'Naira',                                         '₦'),
  ('NIO', 'Cordoba Oro',                                   'C$'),
  ('NOK', 'Norwegian Krone',                               'kr'),
  ('NPR', 'Nepalese Rupee',                                '₨'),
  ('NZD', 'New Zealand Dollar',                            '$'),
  ('OMR', 'Rial Omani',                                    'ر.ع.'),
  ('PAB', 'Balboa',                                        'B/.'),
  ('PEN', 'Nuevo Sol',                                     'S/.'),
  ('PGK', 'Kina',                                          'K'),
  ('PHP', 'Philippine Peso',                               '₱'),
  ('PKR', 'Pakistan Rupee',                                '₨'),
  ('PLN', 'Zloty',                                         'zł'),
  ('PYG', 'Guarani',                                       '₲'),
  ('QAR', 'Qatari Rial',                                   'ر.ق'),
  ('RON', 'Romanian Leu',                                  'lei'),
  ('RSD', 'Serbian Dinar',                                 'din'),
  ('RUB', 'Russian Ruble',                                 '₽'),
  ('RWF', 'Rwanda Franc',                                  'Fr'),
  ('SAR', 'Saudi Riyal',                                   '﷼'),
  ('SBD', 'Solomon Islands Dollar',                        '$'),
  ('SCR', 'Seychelles Rupee',                              '₨'),
  ('SDG', 'Sudanese Pound',                                'ج.س'),
  ('SEK', 'Swedish Krona',                                 'kr'),
  ('SGD', 'Singapore Dollar',                              '$'),
  ('SHP', 'Saint Helena Pound',                            '£'),
  ('SLE', 'Leone',                                         'Le'),
  ('SOS', 'Somali Shilling',                               'Sh'),
  ('SRD', 'Surinam Dollar',                                '$'),
  ('SSP', 'South Sudanese Pound',                          '£'),
  ('STN', 'Dobra',                                         'Db'),
  ('SVC', 'El Salvador Colon',                             '₡'),
  ('SYP', 'Syrian Pound',                                  '£'),
  ('SZL', 'Lilangeni',                                     'L'),
  ('THB', 'Baht',                                          '฿'),
  ('TJS', 'Somoni',                                        'SM'),
  ('TMT', 'Turkmenistan New Manat',                        'T'),
  ('TND', 'Tunisian Dinar',                                'DT'),
  ('TOP', 'Pa''anga',                                      'T$'),
  ('TRY', 'Turkish Lira',                                  '₺'),
  ('TTD', 'Trinidad and Tobago Dollar',                    '$'),
  ('TWD', 'New Taiwan Dollar',                             '$'),
  ('TZS', 'Tanzanian Shilling',                            'Sh'),
  ('UAH', 'Hryvnia',                                       '₴'),
  ('UGX', 'Uganda Shilling',                               'Sh'),
  ('USD', 'US Dollar',                                     '$'),
  ('USN', 'US Dollar (Next day)',                          '$'),
  ('UYI', 'Uruguay Peso en Unidades Indexadas (URUIURUI)', '$'),
  ('UYU', 'Peso Uruguayo',                                 '$'),
  ('UZS', 'Uzbekistan Sum',                                'лв'),
  ('VED', 'Bolívar Digital',                               'Bs.D'),
  ('VEF', 'Bolívar Fuerte',                                'Bs.F'),
  ('VND', 'Dong',                                          '₫'),
  ('VUV', 'Vatu',                                          'Vt'),
  ('WST', 'Tala',                                          'T'),
  ('XAF', 'CFA Franc BEAC',                                'Fr'),
  ('XCD', 'East Caribbean Dollar',                         '$'),
  ('XCG', 'Caribbean Guilder',                             'ƒ'),
  ('XDR', 'SDR (Special Drawing Right)',                   'SDR'),
  ('XOF', 'CFA Franc BCEAO',                               'Fr'),
  ('XPF', 'CFP Franc',                                     'Fr'),
  ('XSU', 'Sucre',                                         'XSU'),
  ('XUA', 'ADB Unit of Account',                           'XUA'),
  ('YER', 'Yemeni Rial',                                   '﷼'),
  ('ZAR', 'Rand',                                          'R'),
  ('ZMW', 'Zambian Kwacha',                                'ZK'),
  ('ZWL', 'Zimbabwe Dollar',                               '$'),
  ('ZWG', 'Zimbabwe Gold',                                 'ZiG')
ON CONFLICT DO NOTHING;
