name: PR Checks

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR Checks - to be implemented"
      - run: echo "Don't forget to update 'PR requirements' ruleset and check 'Require status checks to pass'"
